services:
  ipixel-color-websocket:
    build: .
    container_name: ipixel-color-websocket
    restart: unless-stopped

    network_mode: host

    privileged: true          
    volumes:
      - /var/run/dbus:/var/run/dbus  

    environment:
      - IPIXEL_ADDRESS=${IPIXEL_ADDRESS:-00:00:00:00:00:00}
      - IPIXEL_HOST=${IPIXEL_HOST:-0.0.0.0}
      - IPIXEL_PORT=${IPIXEL_PORT:-5042}
    command: >
      sh -c "python3 -m pypixelcolor.websocket -a $${IPIXEL_ADDRESS} --host $${IPIXEL_HOST} --port $${IPIXEL_PORT:-4444}"